source 'http://rubygems.org/'

gem 'selenium-webdriver'
gem 'faker'
gem 'capybara'
gem 'site_prism'
gem 'cucumber', '~> 3.1.2'
gem 'ffi'
gem 'rspec'
gem 'brazilian_documents'
gem 'cpf_faker'